WIP: Joining up quickstart.sh with quickstarts/aws - issues with passing/validating parameters

diff --git a/quickstarts/aws b/quickstarts/aws
--- a/quickstarts/aws
+++ b/quickstarts/aws
@@ -1,77 +1,25 @@
 #!/bin/bash -e
 
-CMD_NAME=`basename "$0"`
+QUICKSTART_TYPE_NAME="aws"
 
-echo ' 
-      ###    ########   #######  ########  
-     ## ##   ##     ## ##     ## ##     ## 
-    ##   ##  ##     ## ##     ## ##     ## 
-   ##     ## ##     ## ##     ## ########  
-   ######### ##     ## ##     ## ##        
-   ##     ## ##     ## ##     ## ##        
-   ##     ## ########   #######  ##        
-'
+# Debug
+echo "inputs=$@"
 
-echo '
-*****************************************************
-*                  EVALUATION MODE                  *
-*****************************************************
-* Quickstart is designed to get you up and running  *
-* with the DevOps Platform as quickly as possible.  *
-* As such it is not a "production" ready deployment *
-* and therefore we brand it as "evaluation mode".   *
-* In using quickstart you are acknowledging this,   *
-* along with the lack of proper security, backups,  *
-* patching, and other operational considerations.   *
-*****************************************************
-'
-
-usage(){
-   cat <<END_USAGE
-
-Usage:
-        ./quickstart.sh 
-	    -t local 
-	    [-m <MACHINE_NAME>] 
-	    [-u <INITIAL_ADMIN_USER>] 
-	    [-p <INITIAL_ADMIN_PASSWORD>]
-
-        ./quickstart.sh 
-	    -t aws 
-	    -m <MACHINE_NAME> 
-	    -c <AWS_VPC_ID> 
-	    -r <AWS_DEFAULT_REGION> 
-	    [-z <AVAILABILITY_ZONE_LETTER>] 
-	    [-a <AWS_ACCESS_KEY>] 
-	    [-s <AWS_SECRET_ACCESS_KEY>] 
-	    [-u <INITIAL_ADMIN_USER>] 
-	    [-p <INITIAL_ADMIN_PASSWORD>]
-
-END_USAGE
+cmd_desc() {
+    echo "For running quickstart.sh with the AWS provisioner in Docker Machine"
 }
 
-provision_local() {
-    if [ -z ${MACHINE_NAME} ]; then
-        MACHINE_NAME=adop
-    fi
-
-    # Allow script to continue if error returned by docker-machine command
-    set +e
-
-    # Create Docker machine if one doesn't already exist with the same name
-    docker-machine ip ${MACHINE_NAME} > /dev/null 2>&1
-    if [ $? -eq 0 ]; then
-        echo "Docker machine '$MACHINE_NAME' already exists"
-    else
-	# To run adop stack locally atleast 6144 MB is required.
-        docker-machine create --driver virtualbox --virtualbox-memory 6144 ${MACHINE_NAME}
-    fi
-
-    # Reenable errexit
-    set -e
-
+cmd_usage() {
+    echo "usage: ${CMD_NAME} -t ${QUICKSTART_TYPE_NAME} [<options>]"
+    echo "Options:"
+    printf "    %-26s   %s\n" "-m <name>" "The name of the Docker Machine to be created/targetted"
+	printf "    %-26s   %s\n" "-c <aws_vpc_id>" "The AWS VPC ID to launch the machine in"
+	printf "    %-26s   %s\n" "-r <aws_default_region>" "The AWS Region to launch the machine in"
+	printf "    %-26s   %s\n" "-z <az_letter>" "The letter of the availability zone to launch the machine in"
+	printf "    %-26s   %s\n" "-a <aws_access_key>" "The AWS access key to use"
+	printf "    %-26s   %s\n" "-s <aws_secret_access_key>" "The AWS secret access key to use"
 }
-    
+
 # Function to create AWS-specific environment variables file
 source_aws() {  
   AWS_FILE='./conf/provider/env.provider.aws.sh'
@@ -111,15 +59,26 @@ source_aws() {
   fi
   
   sed -i'' -e "s/###AWS_DEFAULT_REGION###/$AWS_DEFAULT_REGION/g" ${AWS_FILE}
-
 }
 
-provision_aws() {
+provision() {
+	echo "Running quickstart provisioner for AWS"
+	
+	# Debug
+	echo "MACHINE_TYPE=$MACHINE_TYPE"
+	echo "MACHINE_NAME=$MACHINE_NAME"
+	echo "INITIAL_ADMIN_USER=$INITIAL_ADMIN_USER"
+	echo "AWS_VPC_ID=$AWS_VPC_ID"
+	echo "AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION"
+	
+	# Setting Compose Opts
+	export CLI_COMPOSE_OPTS="-f etc/aws/default.yml"
+	
     if [ -z ${MACHINE_NAME} ] | \
        [ -z ${AWS_VPC_ID} ] | \
        [ -z ${AWS_DEFAULT_REGION} ]; then
         echo "ERROR: Mandatory parameters missing!"
-        usage
+        cmd_usage
         exit 1
     fi
 
@@ -180,61 +139,35 @@ provision_aws() {
     fi
 }
 
-while getopts "t:m:u:p:h" opt; do
-  case ${opt} in
-    t)
-      export MACHINE_TYPE=${OPTARG}
+# Parameters
+while getopts "c:r:z:a:s:" opt; do
+  case $opt in
+    c)
+      export AWS_VPC_ID=${OPTARG}
       ;;
-    m)
-      export MACHINE_NAME=${OPTARG}
+    r)
+      export AWS_DEFAULT_REGION=${OPTARG}
       ;;
-    u)
-      export INITIAL_ADMIN_USER=${OPTARG}
+    z)
+      export VPC_AVAIL_ZONE=${OPTARG}
       ;;
-    p)
-      export INITIAL_ADMIN_PASSWORD_PLAIN=${OPTARG}
-      ;;      
-    h)
-      usage
-      exit
+    a)
+      export AWS_ACCESS_KEY_ID=${OPTARG}
+      ;;
+    s)
+      export AWS_SECRET_ACCESS_KEY=${OPTARG}
+      ;;
+    *)
+      echo "Invalid parameter(s) or option(s)."
+      cmd_usage
+      exit 1
       ;;
   esac
 done
 
-# Debug
-echo "MACHINE_TYPE=$MACHINE_TYPE"
-echo "MACHINE_NAME=$MACHINE_NAME"
-echo "INITIAL_ADMIN_USER=$INITIAL_ADMIN_USER"
-
-if [ -z ${MACHINE_TYPE} ]; then
-    echo "Please specify a machine type to create during quickstart"
-    usage
-    exit 1
-fi
-
-CLI_COMPOSE_OPTS=""
-
-# Switch based on the machine type
-case ${MACHINE_TYPE} in
-    "local")
-        provision_local
-        ;;
-    "aws")
-        ./quickstarts/aws "$@"
-        ;;
-    *)
-        echo "Invalid parameter(s) or option(s)."
-        usage
-        exit 1
-        ;;
-esac
-
-# Use the ADOP CLI
-eval $(docker-machine env ${MACHINE_NAME})
-
-./adop compose -m "${MACHINE_NAME}" ${CLI_COMPOSE_OPTS} init
-
-# Generate and export Self-Signed SSL certificate for Docker Registry, applicable only for AWS type
-if [ ${MACHINE_TYPE} == "aws" ]; then
-    ./adop certbot gen-export-certs "registry.$(docker-machine ip ${MACHINE_NAME}).nip.io" registry
+# Only run if there are other parameters
+if [ $# -eq 0 ]; then
+    cmd_usage
+else
+	provision
 fi
